import { FeatureType } from '@/enums/feature-type';

const featureTypeCompatibilityMap = new Map<string, FeatureType>([
    ['Text', FeatureType.Text],
    ['text', FeatureType.Text],
    ['Текст', FeatureType.Text],
    ['Ability', FeatureType.Ability],
    ['Здібність', FeatureType.Ability],
    ['Ability Cost', FeatureType.AbilityCost],
    ['Вартість здібності', FeatureType.AbilityCost],
    ['Ability Damage', FeatureType.AbilityDamage],
    ['Шкода здібності', FeatureType.AbilityDamage],
    ['Ability Distance', FeatureType.AbilityDistance],
    ['Дальність здібності', FeatureType.AbilityDistance],
    ['Add-On', FeatureType.AddOn],
    ['Додаток', FeatureType.AddOn],
    ['Ancestry Choice', FeatureType.AncestryChoice],
    ['Вибір походження', FeatureType.AncestryChoice],
    ['Ancestry Feature Choice', FeatureType.AncestryFeatureChoice],
    ['Вибір особливості походження', FeatureType.AncestryFeatureChoice],
    ['Bonus', FeatureType.Bonus],
    ['Бонус', FeatureType.Bonus],
    ['Characteristic Bonus', FeatureType.CharacteristicBonus],
    ['Бонус характеристики', FeatureType.CharacteristicBonus],
    ['Choice', FeatureType.Choice],
    ['Вибір', FeatureType.Choice],
    ['Class Ability', FeatureType.ClassAbility],
    ['Класова здібність', FeatureType.ClassAbility],
    ['Companion', FeatureType.Companion],
    ['Компаньйон', FeatureType.Companion],
    ['Condition Immunity', FeatureType.ConditionImmunity],
    ['Імунітет до станів', FeatureType.ConditionImmunity],
    ['Damage Modifier', FeatureType.DamageModifier],
    ['Модифікатор шкоди', FeatureType.DamageModifier],
    ['Domain', FeatureType.Domain],
    ['Домен', FeatureType.Domain],
    ['Domain Feature', FeatureType.DomainFeature],
    ['Особливість домену', FeatureType.DomainFeature],
    ['Fixture', FeatureType.Fixture],
    ['Фікстура', FeatureType.Fixture],
    ['Follower', FeatureType.Follower],
    ['Прибічник', FeatureType.Follower],
    ['Heroic Resource', FeatureType.HeroicResource],
    ['Героїчний ресурс', FeatureType.HeroicResource],
    ['Heroic Resource Gain', FeatureType.HeroicResourceGain],
    ['Отримання героїчного ресурсу', FeatureType.HeroicResourceGain],
    ['Item Choice', FeatureType.ItemChoice],
    ['Вибір предмета', FeatureType.ItemChoice],
    ['Kit', FeatureType.Kit],
    ['Набір', FeatureType.Kit],
    ['Language', FeatureType.Language],
    ['Мова', FeatureType.Language],
    ['Language Choice', FeatureType.LanguageChoice],
    ['Вибір мови', FeatureType.LanguageChoice],
    ['Malice', FeatureType.Malice],
    ['Злоба', FeatureType.Malice],
    ['Malice Ability', FeatureType.MaliceAbility],
    ['Здібність злоби', FeatureType.MaliceAbility],
    ['Movement Mode', FeatureType.MovementMode],
    ['Режим руху', FeatureType.MovementMode],
    ['Multiple Features', FeatureType.Multiple],
    ['Набір особливостей', FeatureType.Multiple],
    ['Package', FeatureType.Package],
    ['package', FeatureType.Package],
    ['Пакет', FeatureType.Package],
    ['Package Content', FeatureType.PackageContent],
    ['Вміст пакета', FeatureType.PackageContent],
    ['Perk', FeatureType.Perk],
    ['Перевага', FeatureType.Perk],
    ['Proficiency', FeatureType.Proficiency],
    ['Володіння', FeatureType.Proficiency],
    ['Retainer', FeatureType.Retainer],
    ['Ретейнер', FeatureType.Retainer],
    ['Save Threshold', FeatureType.SaveThreshold],
    ['Поріг порятунку', FeatureType.SaveThreshold],
    ['Size', FeatureType.Size],
    ['Розмір', FeatureType.Size],
    ['Skill Choice', FeatureType.SkillChoice],
    ['Вибір навички', FeatureType.SkillChoice],
    ['Speed', FeatureType.Speed],
    ['Швидкість', FeatureType.Speed],
    ['Summon', FeatureType.Summon],
    ['Виклик', FeatureType.Summon],
    ['Summon Choice', FeatureType.SummonChoice],
    ['Вибір виклику', FeatureType.SummonChoice],
    ['Tagged Feature', FeatureType.TaggedFeature],
    ['Позначена особливість', FeatureType.TaggedFeature],
    ['Tagged Feature Choice', FeatureType.TaggedFeatureChoice],
    ['Вибір позначеної особливості', FeatureType.TaggedFeatureChoice],
    ['Title', FeatureType.TitleChoice],
    ['Title Choice', FeatureType.TitleChoice],
    ['Вибір титулу', FeatureType.TitleChoice]
]);

export const normalizeFeatureType = (type: FeatureType | string) => {
    return featureTypeCompatibilityMap.get(type.toString()) ?? type as FeatureType;
};