const skillNameMap: Record<string, string> = {
    Alchemy: 'Алхімія',
    Architecture: 'Архітектура',
    Blacksmithing: 'Ковальство',
    Carpentry: 'Столярство',
    Cooking: 'Кулінарія',
    Fletching: 'Стрільництво',
    Forgery: 'Фальшування',
    Jewelry: 'Ювелірна справа',
    Mechanics: 'Механіка',
    Tailoring: 'Кравецтво',
    Climb: 'Лазіння',
    Drive: 'Водіння',
    Endurance: 'Витривалість',
    Gymnastics: 'Гімнастика',
    Heal: 'Лікування',
    Jump: 'Стрибки',
    Lift: 'Підйом',
    Navigate: 'Навігація',
    Ride: 'Верхова їзда',
    Swim: 'Плавання',
    Brag: 'Вихваляння',
    Empathize: 'Емпатія',
    Empathy: 'Емпатія',
    Flirt: 'Флірт',
    Gamble: 'Азартні ігри',
    'Handle Animals': 'Догляд за тваринами',
    Interrogate: 'Допит',
    Intimidate: 'Залякування',
    Lead: 'Лідерство',
    Lie: 'Брехня',
    Music: 'Музика',
    Perform: 'Виступ',
    Persuade: 'Переконання',
    'Read Person': 'Зчитування людини',
    Alertness: 'Пильність',
    'Conceal Object': 'Приховування предмета',
    Disguise: 'Маскування',
    Eavesdrop: 'Підслуховування',
    'Escape Artist': 'Втеча',
    Hide: 'Ховання',
    'Pick Lock': 'Відмикання замків',
    'Pick Pocket': 'Кишенькова крадіжка',
    Sabotage: 'Диверсія',
    Search: 'Пошук',
    Sneak: 'Крадіжка',
    Track: 'Відстеження',
    Culture: 'Культура',
    'Criminal Underworld': 'Кримінальний світ',
    History: 'Історія',
    Magic: 'Магія',
    Monsters: 'Монстри',
    Nature: 'Природа',
    Psionics: 'Псіоніка',
    Religion: 'Релігія',
    Rumors: 'Чутки',
    Society: 'Суспільство',
    Strategy: 'Стратегія',
    Timescape: 'Таймскейп',
    Сховатись: 'Ховання',
    Крастись: 'Крадіжка'
};

export const normalizeSkillName = (name: string) => {
    const trimmedName = name.trim();
    return skillNameMap[trimmedName] || trimmedName;
};

export const normalizeSkillNames = (names: string[]) => {
    return names.map(normalizeSkillName);
};